include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    sized_box_for_whitespace: false
    sort_unnamed_constructors_first: false
    prefer_relative_imports: true
    avoid_function_literals_in_foreach_calls: false