include: package:lint/analysis_options.yaml

analyzer:
  exclude:
#    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    sized_box_for_whitespace: false
    sort_unnamed_constructors_first: false
    prefer_relative_imports: true