name: slot_machine
description: A slot machine
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.7.0
  bloc: ^7.0.0
  casino_shared:
    path: ../casino_shared
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_circle_color_picker: ^0.3.0
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: ^0.13.3
  logger: ^1.0.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.9.0
  freezed:
  hive_generator:
  lint: 

flutter:
  uses-material-design: true

  assets:
    - assets/classic/
    - assets/emoji/
    - assets/programming/

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"