include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    sort_unnamed_constructors_first: false
    prefer_relative_imports: true