include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    
linter:
  rules:
    sort_unnamed_constructors_first: false
    sort_constructors_first: true
    avoid_classes_with_only_static_members: false
    prefer_single_quotes: true
