name: casino_shared
description: The shared code between the casino controll software and the slotmachines
version: 0.0.1
author: Wim Van Laer
homepage: ""

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  http: ^0.13.3
  logger: ^1.0.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  lint:

flutter:
